export function ComplementLesson({ bn }: { bn: boolean }) {
  return <section className="space-y-4 rounded-xl border border-primary/20 bg-card p-5">
    <h3 className="text-xl font-bold">{bn ? "বিট উল্টে দেখি" : "Let’s flip some bits"}</h3>
    <p className="text-sm leading-7">{bn ? "Complement মানে বিটের মান বদলানো। 1’s complement-এ প্রতিটি 0-কে 1, আর 1-কে 0 করো। 2’s complement পেতে সেই ফলের সঙ্গে 1 যোগ করো। আগে বিটসংখ্যা ঠিক করো—4 বিট হলে সব ধাপে 4 বিট রাখবে।" : "For one’s complement, flip every 0 to 1 and every 1 to 0. For two’s complement, add 1 to that result. Choose the bit width first and keep it throughout."}</p>
    <div className="flex flex-wrap items-center gap-3 rounded-lg bg-muted p-4 font-mono text-lg"><span>0101</span><span>→</span><span>1010</span><span>+ 1 →</span><span>1011</span></div>
    <p className="text-sm text-muted-foreground">{bn ? "মূল সংখ্যা → 1’s complement → 2’s complement" : "Original → one’s complement → two’s complement"}</p>
    <h4 className="font-bold">{bn ? "1 যোগ করার সময়" : "When adding 1"}</h4>
    <p className="text-sm leading-7">{bn ? "এটি বাইনারি যোগ, OR নয়। 1+1 হলে 0 লিখে বাঁয়ে 1 carry দাও। যেমন 1111+1 = 10000। 4 বিটের complement বের করলে অতিরিক্ত বাঁয়ের বিট বাদ দিয়ে 0000 রাখবে।" : "This is binary addition, not OR. For 1+1, write 0 and carry 1 left. For example, 1111+1 = 10000. When finding a four-bit complement, discard the extra left bit and keep 0000."}</p>
    <h4 className="font-bold">{bn ? "ঋণাত্মক সংখ্যা লিখি" : "Writing negative numbers"}</h4>
    <p className="text-sm leading-7">{bn ? "4-bit 2’s complement-এ +3 = 0011; −3 পেতে উল্টে 1100, তারপর 1 যোগে 1101। এই signed পদ্ধতিতে প্রথম বিট 1 হলে সংখ্যা ঋণাত্মক। তার মান জানতে আবার 2’s complement নাও। যেমন 1110 → 0001+1 = 0010, তাই 1110 মানে −2।" : "In four-bit two’s complement, +3 = 0011. For −3, invert to 1100 and add 1: 1101. In this signed format a leading 1 means negative. To find its magnitude, take its two’s complement: 1110 → 0001+1 = 0010, so 1110 means −2."}</p>
    <p className="text-sm leading-7">{bn ? "n-bit signed 2’s complement-এর সীমা −2^(n−1) থেকে 2^(n−1)−1। তাই 4 বিটে −8 থেকে +7। একই 1110 unsigned হলে 14, কিন্তু signed 2’s complement হলে −2—পদ্ধতি জানা জরুরি।" : "The signed n-bit two’s-complement range is −2^(n−1) to 2^(n−1)−1: −8 to +7 for four bits. The same 1110 is 14 unsigned but −2 in signed two’s complement, so the format matters."}</p>
    <h4 className="font-bold">{bn ? "বিয়োগও করা যায়" : "We can subtract too"}</h4>
    <p className="text-sm leading-7">{bn ? "A−B করতে A-এর সঙ্গে B-এর 2’s complement যোগ করো। উদাহরণ 6−2: 0110 + 1110 = 10100 → 4 বিটে 0100 = 4। ফল ঋণাত্মকও হতে পারে: 2−3 = 0010 + 1101 = 1111, অর্থাৎ −1।" : "For A−B, add the two’s complement of B to A. Example: 6−2 gives 0110 + 1110 = 10100; keep four bits, 0100 = 4. A negative result is possible: 2−3 gives 0010 + 1101 = 1111, meaning −1."}</p>
    <h4 className="font-bold">{bn ? "সীমা ছাড়ালে সাবধান" : "Watch the range"}</h4>
    <p className="text-sm leading-7">{bn ? "ফল নির্ধারিত signed সীমার বাইরে গেলে overflow হয়। যেমন 4 বিটে +6+3 = +9 ধরে না; 0110+0011 = 1001-কে সঠিক যোগফল বলা যাবে না। একই চিহ্নের দুটি সংখ্যা যোগ করে বিপরীত চিহ্নের ফল পেলে signed overflow হয়েছে। অতিরিক্ত carry বাদ দেওয়া আর overflow একই বিষয় নয়।" : "Overflow occurs when the result exceeds the signed range. Four bits cannot hold +6+3 = +9: 0110+0011 = 1001 is not the correct signed result. Adding two numbers of the same sign and getting the opposite sign indicates signed overflow. Discarding carry and checking overflow are different operations."}</p>
  </section>;
}
