type Translation = { en: string; bn: string };

export interface LearnQuestion {
  id: number;
  difficulty: "easy" | "medium" | "hard";
  question: Translation;
  options: Translation[];
  correctAnswerIndex: number;
  explanation: Translation;
  topic?: Translation;
  hint?: Translation;
}

export const LEARN_QUESTIONS: LearnQuestion[] = [
  { id: 1, difficulty: "easy", question: { en: "What is A AND B when A = 1 and B = 0?", bn: "A = 1 এবং B = 0 হলে A AND B কত?" }, options: [{ en: "0", bn: "0" }, { en: "1", bn: "1" }], correctAnswerIndex: 0, explanation: { en: "AND outputs 1 only when both inputs are 1.", bn: "দুটি ইনপুটই 1 হলে শুধু AND-এর আউটপুট 1 হয়।" } },
  { id: 2, difficulty: "easy", question: { en: "What is A OR B when A = 0 and B = 1?", bn: "A = 0 এবং B = 1 হলে A OR B কত?" }, options: [{ en: "0", bn: "0" }, { en: "1", bn: "1" }], correctAnswerIndex: 1, explanation: { en: "OR outputs 1 when at least one input is 1.", bn: "অন্তত একটি ইনপুট 1 হলেই OR-এর আউটপুট 1 হয়।" } },
  { id: 3, difficulty: "easy", question: { en: "How many input combinations are in a truth table with three binary inputs?", bn: "তিনটি বাইনারি ইনপুটের ট্রুথ টেবিলে কতটি ইনপুট সমন্বয় থাকে?" }, options: [{ en: "3", bn: "3" }, { en: "6", bn: "6" }, { en: "8", bn: "8" }, { en: "9", bn: "9" }], correctAnswerIndex: 2, explanation: { en: "Each input has two values, so there are 2³ = 8 combinations.", bn: "প্রতিটি ইনপুটের দুটি মান, তাই সমন্বয় সংখ্যা 2³ = 8।" } },
  { id: 4, difficulty: "medium", question: { en: "Which expression equals (A + B)'?", bn: "কোন রাশিটি (A + B)'-এর সমান?" }, options: [{ en: "A' + B'", bn: "A' + B'" }, { en: "A' · B'", bn: "A' · B'" }, { en: "A · B", bn: "A · B" }], correctAnswerIndex: 1, explanation: { en: "De Morgan's first theorem changes OR to AND and complements each input.", bn: "ডি মর্গ্যানের প্রথম সূত্রে OR বদলে AND হয় এবং প্রতিটি ইনপুটের পূরক নেওয়া হয়।" } },
  { id: 5, difficulty: "medium", question: { en: "Expand A · (B + C).", bn: "A · (B + C) বিস্তৃত করো।" }, options: [{ en: "A·B + A·C", bn: "A·B + A·C" }, { en: "A + B·C", bn: "A + B·C" }, { en: "A·B·C", bn: "A·B·C" }], correctAnswerIndex: 0, explanation: { en: "The distributive law applies A to both terms inside the brackets.", bn: "বণ্টন সূত্র অনুযায়ী বন্ধনীর উভয় পদের সঙ্গে A গুণ হয়।" } },
  { id: 6, difficulty: "medium", question: { en: "When A = B = 1, what are XOR and XNOR respectively?", bn: "A = B = 1 হলে যথাক্রমে XOR ও XNOR কত?" }, options: [{ en: "1, 0", bn: "1, 0" }, { en: "1, 1", bn: "1, 1" }, { en: "0, 1", bn: "0, 1" }], correctAnswerIndex: 2, explanation: { en: "XOR is 0 for equal inputs. XNOR is its complement, so it is 1.", bn: "সমান ইনপুটে XOR হয় 0। XNOR তার পূরক, তাই 1।" } },
  { id: 7, difficulty: "easy", question: { en: "What is A + A' for either value of A?", bn: "A-এর যেকোনো মানের জন্য A + A' কত?" }, options: [{ en: "A", bn: "A" }, { en: "0", bn: "0" }, { en: "1", bn: "1" }], correctAnswerIndex: 2, explanation: { en: "One of A and A' is always 1, so their OR is always 1.", bn: "A ও A'-এর একটি সবসময় 1, তাই তাদের OR সবসময় 1।" } },
  { id: 8, difficulty: "medium", question: { en: "Simplify A + A·B.", bn: "A + A·B সরল করো।" }, options: [{ en: "B", bn: "B" }, { en: "A", bn: "A" }, { en: "A + B", bn: "A + B" }], correctAnswerIndex: 1, explanation: { en: "By absorption, A + A·B = A: when A is 0 both terms are 0; when A is 1 the result is 1.", bn: "শোষণ সূত্রে A + A·B = A: A = 0 হলে উভয় পদ 0; A = 1 হলে ফল 1।" } },
  { id: 9, difficulty: "medium", question: { en: "Which expression equals (A · B)'?", bn: "কোন রাশিটি (A · B)'-এর সমান?" }, options: [{ en: "A' + B'", bn: "A' + B'" }, { en: "A' · B'", bn: "A' · B'" }, { en: "A + B", bn: "A + B" }], correctAnswerIndex: 0, explanation: { en: "De Morgan's second theorem changes AND to OR and complements each input.", bn: "ডি মর্গ্যানের দ্বিতীয় সূত্রে AND বদলে OR হয় এবং প্রতিটি ইনপুটের পূরক নেওয়া হয়।" } },
  { id: 10, difficulty: "hard", question: { en: "If A = 0, B = 1, C = 1, what is A·B + A'·C?", bn: "A = 0, B = 1, C = 1 হলে A·B + A'·C কত?" }, options: [{ en: "0", bn: "0" }, { en: "1", bn: "1" }], correctAnswerIndex: 1, explanation: { en: "A·B = 0 and A'·C = 1·1 = 1, so 0 OR 1 = 1.", bn: "A·B = 0 এবং A'·C = 1·1 = 1, তাই 0 OR 1 = 1।" } },
{"id":11,"difficulty":"easy","topic":{"bn":"সুইচ থেকে গেট","en":"Switches and gates"},"question":{"bn":"A = 1, B = 0। AND থেকে OR-এ বদলালে বাতির কী হবে?","en":"A = 1, B = 0. What happens when you change AND to OR?"},"options":[{"bn":"বন্ধ থেকে জ্বলবে","en":"Off to on"},{"bn":"জ্বলা থেকে বন্ধ হবে","en":"On to off"},{"bn":"দুটিতেই বন্ধ","en":"Off for both"},{"bn":"দুটিতেই জ্বলবে","en":"On for both"}],"correctAnswerIndex":0,"explanation":{"bn":"AND-এ দুটোই 1 চাই, তাই ফল 0। OR-এ একটি 1 হলেই চলে, তাই ফল 1।","en":"AND needs both inputs to be 1, so its output is 0. OR needs just one, so its output is 1."},"hint":{"bn":"উপরের বাতির উদাহরণে একই ইনপুট রেখে গেট বদলে দেখো।","en":"In the bulb example above, keep the inputs fixed and change the gate."}},
{"id":12,"difficulty":"medium","topic":{"bn":"সুইচ থেকে গেট","en":"Switches and gates"},"question":{"bn":"বাতি শুধু 00 ও 11-তে জ্বলে। কোন গেট লাগবে?","en":"The bulb lights only for 00 and 11. Which gate do you need?"},"options":[{"bn":"OR","en":"OR"},{"bn":"XOR","en":"XOR"},{"bn":"XNOR","en":"XNOR"},{"bn":"NAND","en":"NAND"}],"correctAnswerIndex":2,"explanation":{"bn":"00 ও 11-তে ইনপুট সমান। XNOR সমান ইনপুটে 1 দেয়। XOR ঠিক উল্টো: 01 ও 10-তে 1 দেয়।","en":"The inputs match in 00 and 11. XNOR gives 1 for matching inputs; XOR instead gives 1 for 01 and 10."},"hint":{"bn":"XOR ভিন্ন ইনপুটে, XNOR সমান ইনপুটে 1 দেয়।","en":"XOR detects different inputs; XNOR detects equal inputs."}},
{"id":13,"difficulty":"medium","topic":{"bn":"শুধু NAND / NOR","en":"NAND / NOR only"},"question":{"bn":"NAND ও NOR-কে universal বলা হয় কেন?","en":"Why are NAND and NOR called universal gates?"},"options":[{"bn":"এগুলো সবসময় 1 দেয়","en":"They always output 1"},{"bn":"যেকোনো এক ধরনের গেট দিয়েই সব বুলিয়ান ফাংশন বানানো যায়","en":"Either type alone can implement every Boolean function"},{"bn":"দুটো একসঙ্গে ব্যবহার করতেই হয়","en":"Both types must be used together"},{"bn":"এগুলোতে ইনপুট লাগে না","en":"They need no inputs"}],"correctAnswerIndex":1,"explanation":{"bn":"শুধু NAND অথবা শুধু NOR দিয়ে NOT, AND ও OR বানানো যায়। তাই যেকোনো বুলিয়ান ফাংশন তৈরি করা সম্ভব; দুটো ধরন একসঙ্গে লাগবেই এমন নয়।","en":"NAND alone or NOR alone can build NOT, AND and OR, and therefore any Boolean function. You do not need both types together."},"hint":{"bn":"উপরের universal gate-এর অংশে মৌলিক গেট তৈরির টেবিল দেখো।","en":"Review the basic-gate construction table in the universal-gate lesson."}},
{"id":14,"difficulty":"medium","topic":{"bn":"শুধু NAND / NOR","en":"NAND / NOR only"},"question":{"bn":"P = A NAND A। A একবার 0, একবার 1 দিলে P যথাক্রমে কত?","en":"P = A NAND A. What is P for A = 0 and then A = 1?"},"options":[{"bn":"0, 1","en":"0, 1"},{"bn":"1, 1","en":"1, 1"},{"bn":"0, 0","en":"0, 0"},{"bn":"1, 0","en":"1, 0"}],"correctAnswerIndex":3,"explanation":{"bn":"A = 0 হলে (0·0)' = 1। A = 1 হলে (1·1)' = 0। একই ইনপুট দুবার দিলে NAND, NOT-এর কাজ করে।","en":"For A = 0, (0·0)' = 1. For A = 1, (1·1)' = 0. Tying the inputs together makes NAND act as NOT."},"hint":{"bn":"NAND মানে আগে AND, তারপর ফল উল্টাও।","en":"NAND means AND first, then invert the result."}},
{"id":15,"difficulty":"hard","topic":{"bn":"শুধু NAND / NOR","en":"NAND / NOR only"},"question":{"bn":"P = A NAND B, F = P NAND P। পুরো সার্কিট কোন গেটের কাজ করে?","en":"P = A NAND B, F = P NAND P. Which gate does the complete circuit implement?"},"options":[{"bn":"AND","en":"AND"},{"bn":"OR","en":"OR"},{"bn":"NAND","en":"NAND"},{"bn":"XOR","en":"XOR"}],"correctAnswerIndex":0,"explanation":{"bn":"প্রথমে P = (AB)'। দ্বিতীয় NAND-এ একই P দুবার, তাই F = P' = ((AB)')' = AB। দুবার পূরক নিলে মূল মান ফিরে আসে।","en":"First P = (AB)'. The second NAND inverts P, so F = P' = ((AB)')' = AB. Double inversion restores the original value."},"hint":{"bn":"একই ইনপুটের NAND হলো NOT; দুবার NOT করলে আগের মান ফেরে।","en":"A NAND with tied inputs acts as NOT; two inversions restore the value."}},
{"id":16,"difficulty":"hard","topic":{"bn":"শুধু NAND / NOR","en":"NAND / NOR only"},"question":{"bn":"P = A NOR A, Q = B NOR B, F = P NOR Q। F কোন রাশির সমান?","en":"P = A NOR A, Q = B NOR B, F = P NOR Q. Which expression equals F?"},"options":[{"bn":"A+B","en":"A+B"},{"bn":"(AB)'","en":"(AB)'"},{"bn":"AB","en":"AB"},{"bn":"A XOR B","en":"A XOR B"}],"correctAnswerIndex":2,"explanation":{"bn":"P = A', Q = B'। তাই F = (A'+B')'। ডি মর্গ্যানের সূত্রে এটি AB। শুধু NOR দিয়ে AND তৈরি হলো।","en":"P = A' and Q = B', so F = (A'+B')'. De Morgan's theorem gives AB: an AND built only from NOR gates."},"hint":{"bn":"NOR আগে OR করে ফল উল্টায়। (X+Y)' = X'Y'।","en":"NOR inverts OR. Use (X+Y)' = X'Y'."}},
{"id":17,"difficulty":"medium","topic":{"bn":"টেবিল থেকে রাশি","en":"Table to expression"},"question":{"bn":"A,B = 00, 01, 10, 11-এর জন্য F = 0, 1, 1, 0। কোন SOP ঠিক?","en":"For A,B = 00, 01, 10, 11, F = 0, 1, 1, 0. Which SOP is correct?"},"options":[{"bn":"AB","en":"AB"},{"bn":"A'B + AB'","en":"A'B + AB'"},{"bn":"A'B' + AB","en":"A'B' + AB"},{"bn":"A+B","en":"A+B"}],"correctAnswerIndex":1,"explanation":{"bn":"F = 1 সারি দুটি 01 ও 10। 01 থেকে A'B, 10 থেকে AB'। OR করলে A'B + AB'—এটিই XOR।","en":"F is 1 for 01 and 10. These give A'B and AB'. OR the minterms: A'B + AB', which is XOR."},"hint":{"bn":"F = 1 সারি বেছে নাও। ইনপুট 0 হলে পূরক, 1 হলে চলক; পদগুলো OR করো।","en":"Choose rows where F = 1. Use a complement for input 0 and the variable for 1, then OR the terms."}},
{"id":18,"difficulty":"hard","topic":{"bn":"টেবিল থেকে রাশি","en":"Table to expression"},"question":{"bn":"F শুধু A,B = 0,1 সারিতে 0। এর canonical POS কী?","en":"F is 0 only for A,B = 0,1. What is its canonical POS?"},"options":[{"bn":"A'B","en":"A'B"},{"bn":"A'+B","en":"A'+B"},{"bn":"A'+B'","en":"A'+B'"},{"bn":"A+B'","en":"A+B'"}],"correctAnswerIndex":3,"explanation":{"bn":"শূন্য সারি 01-এর maxterm-এ A অপরিবর্তিত, B পূরক হবে: A+B'। ওই সারিতে 0+0 = 0; বাকি তিন সারিতে ফল 1।","en":"For the zero row 01, the maxterm uses A and B': A+B'. It is 0+0 = 0 on that row and 1 on the other three."},"hint":{"bn":"POS-এর শূন্য সারিতে ইনপুট 0 হলে চলক, 1 হলে পূরক নিয়ে OR করো।","en":"For a POS zero row, use the variable for input 0 and its complement for 1, joined by OR."}},
{"id":21,"difficulty":"medium","topic":{"bn":"ভুলটা ধরো","en":"Find the mistake"},"question":{"bn":"একজন বলল A + AB = A+B। কোন ইনপুট দিয়ে ভুলটি ধরা যাবে?","en":"Someone claims A + AB = A+B. Which input exposes the mistake?"},"options":[{"bn":"A=0, B=0","en":"A=0, B=0"},{"bn":"A=0, B=1","en":"A=0, B=1"},{"bn":"A=1, B=0","en":"A=1, B=0"},{"bn":"A=1, B=1","en":"A=1, B=1"}],"correctAnswerIndex":1,"explanation":{"bn":"A=0, B=1 হলে মূল রাশি 0+0·1 = 0, কিন্তু A+B = 1। তাই সমান নয়। সঠিক শোষণ সূত্র: A+AB = A।","en":"For A=0, B=1, the original is 0+0·1 = 0, but A+B = 1. They are not equivalent. Absorption gives A+AB = A."},"hint":{"bn":"দুটি রাশি সমান হতে সব ইনপুটে ফল মিলতে হবে। একটি অমিল পেলেই দাবি ভুল।","en":"Equivalent expressions must agree on every input. One mismatch disproves the claim."}},
{"id":19,"difficulty":"easy","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4 বিটে 0101-এর 1’s complement কত?","en":"What is the 4-bit 1’s complement of 0101?"},"options":[{"bn":"1010","en":"1010"},{"bn":"1011","en":"1011"},{"bn":"0100","en":"0100"},{"bn":"1101","en":"1101"}],"correctAnswerIndex":0,"explanation":{"bn":"প্রতিটি বিট উল্টাও: 0→1, 1→0। তাই 0101 → 1010।","en":"Flip every bit: 0101 → 1010."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":20,"difficulty":"easy","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4 বিটে 0101-এর 2’s complement কত?","en":"What is the 4-bit 2’s complement of 0101?"},"options":[{"bn":"1010","en":"1010"},{"bn":"0101","en":"0101"},{"bn":"1011","en":"1011"},{"bn":"1100","en":"1100"}],"correctAnswerIndex":2,"explanation":{"bn":"আগে 1’s complement 1010, তারপর 1 যোগ: 1011।","en":"First invert to 1010, then add 1 to get 1011."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":22,"difficulty":"medium","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4-bit 2’s complement-এ 1110 কোন দশমিক সংখ্যা?","en":"Which decimal number is 1110 in 4-bit two’s complement?"},"options":[{"bn":"14","en":"14"},{"bn":"−1","en":"−1"},{"bn":"2","en":"2"},{"bn":"−2","en":"−2"}],"correctAnswerIndex":3,"explanation":{"bn":"শুরুর বিট 1, তাই ঋণাত্মক। মান পেতে উল্টে 0001, তারপর 1 যোগে 0010 = 2। তাই −2।","en":"The leading 1 means negative. Invert to 0001 and add 1 to get 0010 = 2, so the value is −2."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":23,"difficulty":"easy","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"8 বিটে 00101100-এর 1’s complement কত?","en":"What is the 8-bit 1’s complement of 00101100?"},"options":[{"bn":"11010100","en":"11010100"},{"bn":"11010011","en":"11010011"},{"bn":"10110011","en":"10110011"},{"bn":"00101101","en":"00101101"}],"correctAnswerIndex":1,"explanation":{"bn":"আটটি বিটই উল্টাতে হবে, শুরুর শূন্যসহ: 00101100 → 11010011।","en":"Invert all eight bits, including the leading zeros: 11010011."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":24,"difficulty":"medium","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"8 বিটে 00001100-এর 2’s complement কত?","en":"What is the 8-bit 2’s complement of 00001100?"},"options":[{"bn":"11110011","en":"11110011"},{"bn":"00001101","en":"00001101"},{"bn":"11110100","en":"11110100"},{"bn":"11111100","en":"11111100"}],"correctAnswerIndex":2,"explanation":{"bn":"1’s complement 11110011। এর সঙ্গে 1 যোগ করলে 11110100।","en":"Invert to 11110011, then add 1: 11110100."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":25,"difficulty":"medium","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4-bit 2’s complement-এ −3 কীভাবে লিখবে?","en":"How do you represent −3 in 4-bit two’s complement?"},"options":[{"bn":"1101","en":"1101"},{"bn":"0011","en":"0011"},{"bn":"1100","en":"1100"},{"bn":"1011","en":"1011"}],"correctAnswerIndex":0,"explanation":{"bn":"+3 = 0011। উল্টালে 1100, 1 যোগে 1101।","en":"Start with +3 = 0011. Invert to 1100 and add 1: 1101."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":26,"difficulty":"medium","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4 বিটে 0000-এর 2’s complement কত?","en":"What is the 4-bit 2’s complement of 0000?"},"options":[{"bn":"1111","en":"1111"},{"bn":"0001","en":"0001"},{"bn":"1000","en":"1000"},{"bn":"0000","en":"0000"}],"correctAnswerIndex":3,"explanation":{"bn":"উল্টালে 1111। 1 যোগে 10000; 4 বিট রাখলে 0000।","en":"Invert to 1111 and add 1 to get 10000. Keep four bits: 0000."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":27,"difficulty":"medium","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4-bit signed 2’s complement-এ সংখ্যার সীমা কত?","en":"What is the range of signed 4-bit two’s complement?"},"options":[{"bn":"−7 থেকে +7","en":"−7 to +7"},{"bn":"−8 থেকে +7","en":"−8 to +7"},{"bn":"0 থেকে 15","en":"0 to 15"},{"bn":"−8 থেকে +8","en":"−8 to +8"}],"correctAnswerIndex":1,"explanation":{"bn":"n বিটে সীমা −2^(n−1) থেকে 2^(n−1)−1। n=4 হলে −8 থেকে +7।","en":"For n bits the range is −2^(n−1) to 2^(n−1)−1. With four bits it is −8 to +7."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":28,"difficulty":"hard","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4 বিটে 2’s complement দিয়ে 5−3: 0101 + 1101 = 10010। কোন ফল রাখবে?","en":"For 4-bit subtraction 5−3: 0101 + 1101 = 10010. Which result do you keep?"},"options":[{"bn":"10010","en":"10010"},{"bn":"1101","en":"1101"},{"bn":"0010","en":"0010"},{"bn":"1010","en":"1010"}],"correctAnswerIndex":2,"explanation":{"bn":"বিয়োগের জন্য −3 = 1101 যোগ হয়েছে। বাঁয়ের অতিরিক্ত carry বাদ দিলে 0010 = 2।","en":"Adding 1101 adds −3. Discard the extra carry on the left: 0010 = 2."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":29,"difficulty":"hard","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4-bit 2’s complement-এ 0011 + 1011 = 1110। এটি 3−5-এর কী ফল?","en":"In 4-bit two’s complement, 0011 + 1011 = 1110. What result does this give for 3−5?"},"options":[{"bn":"−2","en":"−2"},{"bn":"14","en":"14"},{"bn":"2","en":"2"},{"bn":"−6","en":"−6"}],"correctAnswerIndex":0,"explanation":{"bn":"1011 হলো −5। ফল 1110 ঋণাত্মক; এর 2’s complement 0010 = 2, তাই ফল −2।","en":"1011 represents −5. The result 1110 is negative; its two’s complement is 0010 = 2, so the result is −2."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
{"id":30,"difficulty":"hard","topic":{"bn":"বিট উল্টে হিসাব","en":"Working with complements"},"question":{"bn":"4-bit signed 2’s complement-এ 0111 + 0001 = 1000। কী ঘটেছে?","en":"In signed 4-bit two’s complement, 0111 + 0001 = 1000. What happened?"},"options":[{"bn":"ফল ঠিকই +8","en":"The result is correctly +8"},{"bn":"Carry বাদ দিলেই +8 হবে","en":"Discarding carry gives +8"},{"bn":"ফল −0","en":"The result is −0"},{"bn":"Overflow: +8 এই সীমায় ধরে না","en":"Overflow: +8 is out of range"}],"correctAnswerIndex":3,"explanation":{"bn":"+7+1 = +8, কিন্তু 4-bit signed সীমার সর্বোচ্চ +7। 1000 মানে −8, তাই এটি সঠিক যোগফল নয়; overflow হয়েছে।","en":"7+1 = 8, but the maximum signed 4-bit value is 7. 1000 represents −8, so overflow has occurred."},"hint":{"bn":"উপরের complement-এর পাঠ দেখো। বিটসংখ্যা ঠিক রাখো; 1’s-এ বিট উল্টাও, 2’s-এ এরপর 1 যোগ করো।","en":"Review the complement lesson above. Keep the bit width: invert for one's complement, then add 1 for two's complement."}},
].sort((a, b) => a.id - b.id) as LearnQuestion[];
